<h1><span style="background-color: #79ea7f;"># Modelo para predecir una Solicitud de cr&eacute;dito</span></h1>

<h3 data-start="128" data-end="166">&iquest;Qu&eacute; hace get_data('credit')?</h3>
<p data-start="168" data-end="312">Es una funci&oacute;n de PyCaret que descarga un dataset de ejemplo llamado "credit", que simula datos relacionados con solicitudes de cr&eacute;dito.</p>
<h3 data-start="314" data-end="356">Descripci&oacute;n del dataset "credit":</h3>
<ul data-start="358" data-end="629">
<li data-start="358" data-end="425">
<p data-start="360" data-end="425">Origen: PyCaret datasets (no es un dataset externo como UCI).</p>
</li>
<li data-start="426" data-end="541">
<p data-start="428" data-end="541">Contenido t&iacute;pico:<br data-start="449" data-end="452" />Incluye variables como ingresos, edad, duraci&oacute;n del cr&eacute;dito, historial de cr&eacute;dito, etc.</p>
</li>
<li data-start="542" data-end="629">
<p data-start="544" data-end="629">Objetivo: Predecir si una solicitud de cr&eacute;dito ser&aacute; buena (1) o mala (0)</p>
</li>
</ul>

<p><a href="https://pycaret.gitbook.io/docs">https://pycaret.gitbook.io/docs</a></p>

Importamos las librerias Necesarias

In [87]:
import pandas as pd
from pycaret.datasets import get_data

Cargamos el Dataset.

In [88]:
dataset = get_data('credit')

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,90000,2,2,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
2,50000,2,2,1,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
3,50000,1,2,1,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
4,50000,1,1,2,37,0,0,0,0,0,...,19394.0,19619.0,20024.0,2500.0,1815.0,657.0,1000.0,1000.0,800.0,0

En este caso elegimos una muestra del 95% de los datos del Datadaset

In [89]:
data = dataset.sample(frac=.95, random_state=0)
data

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
5118,50000,2,1,1,40,-1,2,-1,-1,2,...,1360.0,518.0,3518.0,0.0,760.0,600.0,0.0,3000.0,0.0,1
10284,50000,1,3,1,43,0,0,0,0,0,...,18301.0,18639.0,18516.0,1303.0,1274.0,633.0,1000.0,724.0,1000.0,0
6208,180000,2,1,1,35,0,0,0,0,0,...,60607.0,67976.0,20412.0,5705.0,3003.0,10607.0,7976.0,5412.0,2460.0,0
3361,80000,1,2,2,28,0,0,0,0,0,...,26034.0,26615.0,28173.0,1412.0,1425.0,931.0,1000.0,2000.0,2000.0,0
7068,220000,2,1,1,36,0,0,0,0,0,...,37975.0,39752.0,33351.0,9005.0,10000.0,15000.0,9000.0,21000.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12261,160000,2,3,1,44,0,-1,-1,2,2,...,2313.0,2753.0,2191.0,2000.0,3037.0,0.0,1000.0,0.0,5000.0,0
9079,200000,2,1,1,34,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
16057,240000,2,1,1,35,-1,-1,-1,0,-1,...,4578.0,5928.0,5619.0,5770.0,10420.0,1150.0,5928.0,3619.0,13227.0,1
7116,140000,2,1,2,25,-1,-1,-1,-1,-1,...,643.0,2561.0,1440.0,1844.0,1311.0,643.0,2561.0,1440.0,1582.0,0
8686,150000,2,3,2,60,0,0,0,0,0,...,100508.0,102610.0,101682.0,6780.0,4800.0,3496.0,3618.0,4000.0,3497.0,1

In [90]:
data.shape

(22800, 24)

El dataset Restante lo guardamos en otro DF, nos servirÃ¡ como otro subconjunto para evaluar el modelo

In [91]:
data_unseen = dataset.drop(data.index)
data_unseen

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
62,240000,2,2,2,44,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
63,470000,2,3,3,33,0,0,0,0,0,...,69923.0,29271.0,29889.0,6400.0,7566.0,3000.0,960.0,1000.0,3000.0,0
79,50000,2,3,1,22,0,0,0,0,0,...,13150.0,8866.0,7899.0,1411.0,1194.0,379.0,281.0,321.0,197.0,0
93,50000,1,2,2,41,0,0,0,0,0,...,20274.0,20311.0,19957.0,1340.0,1305.0,700.0,718.0,724.0,684.0,0
99,310000,2,2,1,35,2,0,0,0,0,...,258610.0,246491.0,198889.0,13019.0,11128.0,8407.0,8599.0,6833.0,5987.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23855,30000,1,2,2,34,0,0,0,0,0,...,20929.0,21280.0,21724.0,2000.0,2000.0,2000.0,1000.0,787.0,1133.0,0
23902,180000,1,1,1,37,1,-1,-1,-1,-1,...,919.0,500.0,7068.0,2701.0,1832.0,919.0,500.0,7068.0,9268.0,0
23927,190000,1,1,2,33,0,0,0,0,0,...,120826.0,112211.0,110396.0,6388.0,6112.0,4202.0,4200.0,4200.0,5000.0,0
23933,50000,1,2,1,40,0,0,0,0,0,...,44356.0,19344.0,19354.0,1691.0,1942.0,1296.0,674.0,693.0,1000.0,0
23935,50000,1,3,1,46,3,3,2,0,0,...,50033.0,9779.0,9924.0,0.0,7.0,1104.0,445.0,400.0,204.0,0

In [92]:
#Reseteamos los indices
data.reset_index(inplace= True, drop=True)
data_unseen.reset_index(inplace=True, drop= True)

In [93]:
#importamos la libreria para utilizar Pycaret
from pycaret.classification import *

In [94]:
# Elegimos los parametros del Setup, intoducimos el dataset = data, y la variable objetivo Target= default, fix_imbalance= true para aplicar Smote para desblanceo de  clases
model_setup = setup(data= data, target="default", session_id=123 , fix_imbalance=True)

<p><strong data-start="119" data-end="154">Conclusi&oacute;n del setup en PyCaret</strong></p>
<p data-start="156" data-end="498">El experimento fue configurado para un problema de clasificaci&oacute;n binaria con el objetivo de predecir la variable <strong data-start="269" data-end="282">"default"</strong> en un dataset original de 22,800 registros y 24 caracter&iacute;sticas. Tras aplicar preprocesamiento, la muestra aument&oacute; a 31,721 registros, distribuidos en un conjunto de entrenamiento de 24,880 y uno de prueba de 6,841.</p>
<p data-start="500" data-end="798">Se usaron 23 variables num&eacute;ricas, con imputaci&oacute;n simple basada en la media para valores faltantes num&eacute;ricos y la moda para categ&oacute;ricos. Para corregir el desequilibrio de clases se aplic&oacute; la t&eacute;cnica <strong data-start="698" data-end="707">SMOTE</strong>. La validaci&oacute;n cruzada se realiz&oacute; con un generador de pliegues estratificados de 10 folds.</p>
<p data-start="800" data-end="917">El setup se ejecut&oacute; sin GPU y sin registro de experimentos externos, utilizando todos los n&uacute;cleos de CPU disponibles.</p>
<p>&nbsp;</p>

In [95]:
#Modelos que podemos probar
models()

,Name,Reference,Turbo
ID,,,
lr,Logistic Regression,sklearn.linear_model._logistic.LogisticRegression,True
knn,K Neighbors Classifier,sklearn.neighbors._classification.KNeighborsCl...,True
nb,Naive Bayes,sklearn.naive_bayes.GaussianNB,True
dt,Decision Tree Classifier,sklearn.tree._classes.DecisionTreeClassifier,True
svm,SVM - Linear Kernel,sklearn.linear_model._stochastic_gradient.SGDC...,True
rbfsvm,SVM - Radial Kernel,sklearn.svm._classes.SVC,False
gpc,Gaussian Process Classifier,sklearn.gaussian_process._gpc.GaussianProcessC...,False
mlp,MLP Classifier,sklearn.neural_network._multilayer_perceptron....,False
ridge,Ridge Classifier,sklearn.linear_model._ridge.RidgeClassifier,True
rf,Random Forest Classifier,sklearn.ensemble._forest.RandomForestClassifier,True
qda,Quadratic Discriminant Analysis,sklearn.discriminant_analysis.QuadraticDiscrim...,True
ada,Ada Boost Classifier,sklearn.ensemble._weight_boosting.AdaBoostClas...,True
gbc,Gradient Boosting Classifier,sklearn.ensemble._gb.GradientBoostingClassifier,True
lda,Linear Discriminant Analysis,sklearn.discriminant_analysis.LinearDiscrimina...,True
et,Extra Trees Classifier,sklearn.ensemble._forest.ExtraTreesClassifier,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMClassifier,True
dummy,Dummy Classifier,sklearn.dummy.DummyClassifier,True

In [96]:
#Hacemos una comparacion de modelos para elegir dos modelos y optimizarlos
best_model = compare_models()

## Lightgbm

In [97]:
#Optimizamos el primero modelo.
lg = create_model("lightgbm")

In [98]:
#Optimizamos el mismo modelo pero tratando de mejorar el recall y f1
lg2 = create_model("lightgbm", scale_pos_weight=3.5231813041839426)

In [99]:
print(lg2)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=123, reg_alpha=0.0, reg_lambda=0.0,
               scale_pos_weight=3.5231813041839426, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

In [100]:
# Buscamos los mejores hiperparametros para el modelo original
tuned_lg = tune_model(lg)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [101]:
#Buscamos los mejores hiperparametros para el modelo que busca balancear mas ambas clases
tuned_lg2 = tune_model(lg2)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [102]:
#evaluacion del modelo original
evaluate_model(tuned_lg)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

In [103]:
#evaluacion del modelo con scale_pos_weight
evaluate_model (tuned_lg2)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

<p><strong>Modelo original</strong></p>
<p>Mejor desempe&ntilde;o general: accuracy (82.2%), AUC (0.7789), F1 Score (0.4895), MCC (0.4119).</p>
<p>Pero su recall promedio es bajo (38.8%), lo que indica que pierde muchos casos positivos (clase 1).</p>
<p><strong>Modelo con scale_pos_weight</strong></p>
<p>Sacrifica algo de precisi&oacute;n global (accuracy baja a 75.9%), pero mejora notablemente el recall (57.0%), lo que significa que detecta m&aacute;s casos positivos.</p>
<p>Tiene un F1 Score ligeramente superior (0.5114), lo que refleja mejor balance entre precisi&oacute;n y recall.</p>

<h3 data-start="984" data-end="1005"><strong data-start="991" data-end="1005">Conclusi&oacute;n</strong></h3>
<ul data-start="1006" data-end="1276">
<li data-start="1006" data-end="1161">
<p data-start="1008" data-end="1161">Si es m&aacute;s importante detectar los casos positivos (clase 1), el modelo con scale_pos_weight es preferible por su mayor recall y mejor F1 Score.</p>
</li>
<li data-start="1162" data-end="1276">
<p data-start="1164" data-end="1276">Si se prioriza el desempe&ntilde;o global y el balance entre clases no es un problema, el modelo original es mejor.</p>
</li>
</ul>

## Random Forest

In [104]:
#Creamos el modelo Random Forest, aplicamos class weight tratando de balancear las clases
rf = create_model("rf", class_weight='balanced')

In [105]:
#Observamos los hiperparametros que tiene originalmente
print (rf)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=-1,
                       oob_score=False, random_state=123, verbose=0,
                       warm_start=False)

In [106]:
#buscamos los hiperparametros optimos , optimizamos f1 para darle mas peso a la clase 1
tuned_rf = tune_model(rf, optimize='F1')

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [107]:
#Hiperparametros optimos
print(tuned_rf)

RandomForestClassifier(bootstrap=False, ccp_alpha=0.0,
                       class_weight='balanced_subsample', criterion='gini',
                       max_depth=4, max_features='sqrt', max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.0005,
                       min_samples_leaf=3, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, monotonic_cst=None,
                       n_estimators=260, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)

In [108]:
#Metricas del modelo Random Forest
evaluate_model(tuned_rf)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

### Comparar Modelos

In [109]:
#Metricas generadas con las predicciones del conjunto de prueba que nos separo pycaret (30% del dataset)
# PredicciÃ³n con el primer modelo (Lightgmb)
results1_1 = predict_model(tuned_lg)
metrics1_1 = pull()  # <-- inmediatamente despuÃ©s

# PredicciÃ³n con el segundo modelo (Random Forest) 
results2_1 = predict_model(tuned_rf)
metrics2_1 = pull()  # <-- inmediatamente despuÃ©s

[LightGBM] [Warning] feature_fraction is set=0.9, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9
[LightGBM] [Warning] bagging_fraction is set=0.6, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4
[LightGBM] [Warning] feature_fraction is set=0.9, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9
[LightGBM] [Warning] bagging_fraction is set=0.6, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4

In [110]:
#Impresion de metricas
print(metrics1_1)
print(metrics2_1)

                             Model  Accuracy     AUC  Recall   Prec.      F1  \
0  Light Gradient Boosting Machine    0.8186  0.7763  0.3654  0.6599  0.4703

    Kappa     MCC
0  0.3716  0.3953
                      Model  Accuracy     AUC  Recall   Prec.      F1   Kappa  \
0  Random Forest Classifier    0.7978  0.7617   0.506  0.5446  0.5246  0.3964

      MCC
0  0.3969

In [111]:
#Metricas generadas con las predicciones del conjunto que separamos inicialmente.
# PredicciÃ³n con el primer modelo
results1_2 = predict_model(tuned_lg, data=data_unseen)
metrics1_2 = pull()  # <-- inmediatamente despuÃ©s

# PredicciÃ³n con el segundo modelo
results2_2 = predict_model(tuned_rf, data=data_unseen)
metrics2_2 = pull()  # <-- inmediatamente despuÃ©s

[LightGBM] [Warning] feature_fraction is set=0.9, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9
[LightGBM] [Warning] bagging_fraction is set=0.6, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4
[LightGBM] [Warning] feature_fraction is set=0.9, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9
[LightGBM] [Warning] bagging_fraction is set=0.6, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4

In [112]:
print(metrics1_2)
print(metrics2_2)

                             Model  Accuracy    AUC  Recall   Prec.      F1  \
0  Light Gradient Boosting Machine    0.8158  0.778  0.3763  0.6908  0.4872

    Kappa     MCC
0  0.3867  0.4132
                      Model  Accuracy     AUC  Recall   Prec.      F1   Kappa  \
0  Random Forest Classifier    0.7917  0.7603  0.5054  0.5573  0.5301  0.3967

      MCC
0  0.3974

<p data-start="93" data-end="108"><strong data-start="93" data-end="108">Conclusi&oacute;n:</strong></p>
<p data-start="110" data-end="671">Los resultados obtenidos con PyCaret y con el subconjunto extra&iacute;do del 5% del dataset son consistentes entre s&iacute;, mostrando un desempe&ntilde;o similar para ambos modelos evaluados. El modelo Light Gradient Boosting Machine presenta una ligera ventaja en Accuracy, AUC y Precisi&oacute;n, mientras que el Random Forest Classifier muestra un mejor Recall y m&eacute;tricas equilibradas como F1, Kappa y MCC. En general, ambos modelos tienen un rendimiento comparable y podr&iacute;an considerarse adecuados para el problema, aunque LightGBM podr&iacute;a ser preferible si se prioriza la precisi&oacute;n.</p>

## Guardar el Mejor modelo

In [119]:
final_rf = finalize_model(tuned_lg)

In [120]:
print(final_rf)

Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['LIMIT_BAL', 'SEX', 'EDUCATION',
                                             'MARRIAGE', 'AGE', 'PAY_1',
                                             'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5',
                                             'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
                                             'BILL_AMT3', 'BILL_AMT4',
                                             'BILL_AMT5', 'BILL_AMT6',
                                             'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
                                             'PAY_AMT4', 'PAY_AMT5',
                                             'PAY_AMT6'],
                                    transform...
                                boosting_type='gbdt', class_weight=None,
                                colsample_bytree=1.0, feature_fraction=0.9,
                                importance_type='split', learning_rate=0.05,
                                max_depth=-1, min_child_samples=96,
                                min_child_weight=0.001, min_split_gain=0.7,
                                n_estimators=180, n_jobs=-1, num_leaves=10,
                                objective=None, random_state=123,
                                reg_alpha=0.0001, reg_lambda=0.1, subsample=1.0,
                                subsample_for_bin=200000, subsample_freq=0))],
         verbose=False)

In [121]:
save_model(final_rf, "Final_RF_Model_26May2023")

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['LIMIT_BAL', 'SEX', 'EDUCATION',
                                              'MARRIAGE', 'AGE', 'PAY_1',
                                              'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5',
                                              'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
                                              'BILL_AMT3', 'BILL_AMT4',
                                              'BILL_AMT5', 'BILL_AMT6',
                                              'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
                                              'PAY_AMT4', 'PAY_AMT5',
                                              'PAY_AMT6'],
                                     transform...
                                 boosting_type='gbdt', class_weight=None,
                                 colsample_bytree=1.0, feature_fraction=0.9,
                                 importance_type='split', learning_rate=0.05,
                                 max_depth=-1, min_child_samples=96,
                                 min_child_weight=0.001, min_split_gain=0.7,
                                 n_estimators=180, n_jobs=-1, num_leaves=10,
                                 objective=None, random_state=123,
                                 reg_alpha=0.0001, reg_lambda=0.1, subsample=1.0,
                                 subsample_for_bin=200000, subsample_freq=0))],
          verbose=False),
 'Final_RF_Model_26May2023.pkl')